# Generated by Django 5.1.6 on 2025-03-12 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0004_alter_user_managers_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bicycle', 'Bicycle'), ('car', 'Car'), ('truck', 'Truck'), ('van', 'Van'), ('motorcycle', 'Motorcycle')], max_length=255)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
