# Generated by Django 5.1.6 on 2025-03-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0004_alter_user_managers_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pictures/%(name)s/'),
        ),
    ]
