# Generated by Django 5.1.6 on 2025-03-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0005_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
