# Generated by Django 5.1.6 on 2025-03-13 17:43

import vehicleLending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0005_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=vehicleLending.models.user_directory_path),
        ),
    ]
