# Generated by Django 5.1.6 on 2025-03-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0006_vehicle_details_vehicle_isavailable_vehicle_make_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='isAvailable',
            new_name='is_available',
        ),
    ]
