# Generated by Django 5.1.6 on 2025-03-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0007_rename_isavailable_vehicle_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('vehicles', models.ManyToManyField(related_name='collections', to='vehicleLending.vehicle')),
            ],
        ),
    ]
