# Generated by Django 5.1.6 on 2025-03-15 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0007_alter_user_profile_pic'),
        ('vehicleLending', '0007_rename_isavailable_vehicle_is_available'),
    ]

    operations = [
    ]
