# Generated by Django 5.1.6 on 2025-03-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0008_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.URLField(blank=True, default='https://media.istockphoto.com/id/1055079680/vector/black-linear-photo-camera-like-no-image-available.jpg?s=612x612&w=0&k=20&c=P1DebpeMIAtXj_ZbVsKVvg-duuL0v9DlrOZUvPG6UJk=', null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='collections', to='vehicleLending.vehicle'),
        ),
    ]
