# Generated by Django 5.1.6 on 2025-03-15 00:53

import vehicleLending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0008_merge_20250315_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vehicleLending.models.vehicle_directory_path),
        ),
    ]
