# Generated by Django 5.1.6 on 2025-03-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0009_alter_collection_image_alter_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patron', 'Patron'), ('librarian', 'Librarian')], default='patron', max_length=10),
        ),
    ]
