# Generated by Django 5.1.6 on 2025-03-16 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0010_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='private_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='users_with_access',
            field=models.ManyToManyField(blank=True, related_name='private_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
