# Generated by Django 5.1.6 on 2025-03-17 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0009_vehicle_image'),
        ('vehicleLending', '0011_collection_private_collection_and_more'),
    ]

    operations = [
    ]
