# Generated by Django 5.1.6 on 2025-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0012_merge_20250317_0016'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='type',
            new_name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='details',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default='Unknown Make', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='Unknown Model', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(default='Unknown Year', max_length=255),
        ),
    ]
