# Generated by Django 5.1.6 on 2025-03-31 03:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0014_collection_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_requested',
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=255)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='vehicleLending.vehicle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'requester'), name='unique_vehicle_requester')],
            },
        ),
    ]
