# Generated by Django 5.1.6 on 2025-04-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0015_remove_vehicle_is_requested_borrowrequest'),
    ]
