# Generated by Django 5.1.6 on 2025-04-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0019_collectionaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='private_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection', to='vehicleLending.collection'),
        ),
    ]
