# Generated by Django 5.1.6 on 2025-04-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleLending', '0020_vehicle_latitude_vehicle_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
