# Generated by Django 5.1.6 on 2025-04-29 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleLending", "0020_vehicle_private_collection"),
        ("vehicleLending", "0021_alter_vehicle_latitude_alter_vehicle_longitude"),
    ]

    operations = []
