# Generated by Django 5.1.6 on 2025-04-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleLending", "0022_merge_20250429_1727"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrequest",
            name="seen_by_requester",
            field=models.BooleanField(default=False),
        ),
    ]
