# Generated by Django 5.1.6 on 2025-04-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleLending", "0023_borrowrequest_seen_by_requester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowrequest",
            name="seen_by_requester",
        ),
    ]
