# Generated by Django 5.1.6 on 2025-04-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleLending", "0023_remove_vehicle_image_vehicleimage"),
        ("vehicleLending", "0024_remove_borrowrequest_seen_by_requester"),
    ]

    operations = []
